### ISSUE TITLE
loading files 

### ISSUE THREAD

**Issue by lhamon31** [lhamon31/butterfliesNC#3]
@ahhurlbert still having trouble getting 'temp' files to load because they're not being recognized as valid- I had the code for this in the console history but it has since been deleted

**Comment by ahhurlbert** [comment]
I can't test your code since I don't actually have the raw data files on my computer, but what we did earlier was use

`files = list.files()`

assuming your working directory is set to be where those raw files are. Then you don't have to worry about typos in the path or file name because you could just do something like

`temp.jan1990 = raster(files[1])`

or

`temp.1990 = stack(files)`

See if something like that will work.

**Comment by lhamon31** [comment]
That worked. Thank you!
